# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: social.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'social.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csocial.proto\x12\x06social\"5\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"5\n\x10RegisterResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\"\x1f\n\x0eProfileRequest\x12\r\n\x05token\x18\x01 \x01(\t\"4\n\x0fProfileResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\"1\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\"!\n\x11\x43reatePostRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"0\n\x12\x43reatePostResponse\x12\x1a\n\x04post\x18\x01 \x01(\x0b\x32\x0c.social.Post\"\x11\n\x0fGetPostsRequest\"/\n\x10GetPostsResponse\x12\x1b\n\x05posts\x18\x01 \x03(\x0b\x32\x0c.social.Post2\xc5\x01\n\x0b\x41uthService\x12=\n\x08Register\x12\x17.social.RegisterRequest\x1a\x18.social.RegisterResponse\x12\x34\n\x05Login\x12\x14.social.LoginRequest\x1a\x15.social.LoginResponse\x12\x41\n\x0eGetUserProfile\x12\x16.social.ProfileRequest\x1a\x17.social.ProfileResponse2\x91\x01\n\x0bWallService\x12\x43\n\nCreatePost\x12\x19.social.CreatePostRequest\x1a\x1a.social.CreatePostResponse\x12=\n\x08GetPosts\x12\x17.social.GetPostsRequest\x1a\x18.social.GetPostsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'social_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=24
  _globals['_REGISTERREQUEST']._serialized_end=77
  _globals['_REGISTERRESPONSE']._serialized_start=79
  _globals['_REGISTERRESPONSE']._serialized_end=132
  _globals['_LOGINREQUEST']._serialized_start=134
  _globals['_LOGINREQUEST']._serialized_end=184
  _globals['_LOGINRESPONSE']._serialized_start=186
  _globals['_LOGINRESPONSE']._serialized_end=216
  _globals['_PROFILEREQUEST']._serialized_start=218
  _globals['_PROFILEREQUEST']._serialized_end=249
  _globals['_PROFILERESPONSE']._serialized_start=251
  _globals['_PROFILERESPONSE']._serialized_end=303
  _globals['_POST']._serialized_start=305
  _globals['_POST']._serialized_end=354
  _globals['_CREATEPOSTREQUEST']._serialized_start=356
  _globals['_CREATEPOSTREQUEST']._serialized_end=389
  _globals['_CREATEPOSTRESPONSE']._serialized_start=391
  _globals['_CREATEPOSTRESPONSE']._serialized_end=439
  _globals['_GETPOSTSREQUEST']._serialized_start=441
  _globals['_GETPOSTSREQUEST']._serialized_end=458
  _globals['_GETPOSTSRESPONSE']._serialized_start=460
  _globals['_GETPOSTSRESPONSE']._serialized_end=507
  _globals['_AUTHSERVICE']._serialized_start=510
  _globals['_AUTHSERVICE']._serialized_end=707
  _globals['_WALLSERVICE']._serialized_start=710
  _globals['_WALLSERVICE']._serialized_end=855
# @@protoc_insertion_point(module_scope)
